# Generated by Django 4.0.8 on 2022-11-08 09:28

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(max_length=55, unique=True, verbose_name='Key')),
                ('status', models.CharField(choices=[('INACTIVE', 'InActive'), ('ACTIVE', 'Active')], default='INACTIVE', max_length=55)),
            ],
            options={
                'verbose_name': 'LicenseKey',
                'verbose_name_plural': 'LicenseKeys',
            },
        ),
    ]
