# Generated by Django 4.0.8 on 2022-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_licensekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active')], default='INACTIVE', max_length=55),
        ),
    ]
